Algoritmo "notas"

Var

    nota1, nota2, final: real

Inicio

        escreva ("Digite a primeira nota: ")
        leia (nota1)
        escreva ("Digite a segunda nota: ")
        leia (nota2)

        final <- nota1 + nota2
        escreva ("NOTA FINAL: ", final:5:1)
        escreval
         se nota1 <60 entao
            escreval ("REPROVADO")
         senao
            escreva ("APROVADO")
        fimse


Fimalgoritmo
